{
  "openapi": "3.0.1",
  "info": {
    "title": "Pan Generator API",
    "description": "Generates PAN for different card schemes",
    "contact": {
      "name": "Chukwuemeka Vin-Anuonye",
      "email": "chib.vinan@gmail.com"
    },
    "license": {
      "name": "Terms of Use",
      "url": "https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt"
    },
    "version": "v1.0"
  },
  "servers": [
    {
      "url": "http://localhost:9993"
    }
  ],
  "paths": {
    "/api/v1/pan-generator/mobile/pans": {
      "post": {
        "tags": [
          "Generate Pan"
        ],
        "summary": "This operation generates a PAN for the specified card scheme using the mobile number provided",
        "description": "GENERATES PAN USING MOBILE NUMBER AND CARD SCHEME",
        "operationId": "01",
        "requestBody": {
          "description": "generate pan using mobile number and card scheme",
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "mobileNumber": "080XXXXXXXX",
                "cardScheme": "Verve",
                "isGlobalVerveCard": false
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "example": {
                  "pan": "5555555555555555",
                  "responseStatus": "SUCCESSFUL"
                }
              }
            }
          },
          "400": {
            "description": "Invalid mobileNumber",
            "content": {
              "application/json": {
                "example": {
                  "responseStatus": "INVALID_REQUEST",
                  "error": {
                    "errorMessage": "MobileNumber must be 11 digits long"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing card scheme",
            "content": {
              "application/json": {
                "example": {
                  "responseStatus": "INVALID_REQUEST",
                  "error": {
                    "errorMessage": "cardScheme should not be empty"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/pan-generator/random/pans": {
      "post": {
        "tags": [
          "Generate Pan"
        ],
        "summary": "This operation generates a random PAN for the supplied card scheme",
        "description": "GENERATES RANDOM PAN FOR PROVIDED CARD SCHEME",
        "operationId": "02",
        "requestBody": {
          "description": "generate random pan for provided card scheme",
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "cardScheme": "Verve",
                "isGlobalVerveCard": true
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "example": {
                  "pan": "5555555555555555",
                  "responseStatus": "SUCCESSFUL"
                }
              }
            }
          },
          "400": {
            "description": "Missing card scheme",
            "content": {
              "application/json": {
                "example": {
                  "responseStatus": "INVALID_REQUEST",
                  "error": {
                    "errorMessage": "cardScheme should not be empty"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/pan-generator/pans/{pageNumber}/{pageSize}": {
      "get": {
        "tags": [
          "Get Pan(s)"
        ],
        "summary": "This operation returns a list of Pans",
        "description": "RETRIEVES A LIST OF PANs USING PAGINATION",
        "parameters": [
          {
            "name": "pageNumber",
            "in": "path",
            "description": "The page number to be returned",
            "required": true,
            "allowEmptyValue": false,
            "example": 1
          },
          {
            "name": "pageSize",
            "in": "path",
            "description": "The number of pages to be returned",
            "required": true,
            "allowEmptyValue": false,
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "example": {
                  "responseStatus": "SUCCESSFUL",
                  "pans": [
                    {
                      "id": "5gf434fe",
                      "cardNumber": "5555555555555555"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/pan-generator/pans": {
      "get": {
        "tags": [
          "Get Pan(s)"
        ],
        "summary": "This operation retrieves a Pan using the unique id  tied to the Pan",
        "description": "Retrieves a Pan",
        "parameters": [
          {
            "name": "panUid",
            "in": "query",
            "description": "The UID mapped to the Pan",
            "required": true,
            "allowEmptyValue": false,
            "example": "543r-32egt-534g"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "example": {
                  "pan": "5555555555555555",
                  "responseStatus": "SUCCESSFUL"
                }
              }
            }
          },
          "404": {
            "description": "No Record Found",
            "content": {
              "application/json": {
                "example": {
                  "responseStatus": "NO_RECORD_FOUND"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {}
}